### ISSUE TITLE
default urlInterval when using urlTemplates

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#141]
The default `__init__` value for urlInterval, in TimeseriesFactory.py,  is -1, which if you look at Util.getIntervals() you will quickly see how this might be a problem (i.e., it leads to an infinite while loop, and rather ugly memory leak/flood). In fact, this bit me the **very** first time I attempted to use a urlTemplate with the IAGA2002 factory.

I see how to fix my immediate problem by explicitly setting the urlInterval when I initialize the factory, but I don't think this is the intended default behavior, especially since the docs state explicitly that the default interval should be 86400 seconds.

And while this seems like a simple fix, the ease with which I uncovered this nasty little bug makes me worry that there is something more fundamentally flawed in the way I first attempted to use urlTemplates. Therefore I'll just put this comment here to motivate discussion (and personal enlightenment), and refrain from submitting a pull request for now.

**Comment by jmfee-usgs** [comment]
More information about how you were using the url template would be useful, generally the interval needs to be specified and maybe additional warnings should be generated when using a template without a specific interval.

**Comment by erigler-usgs** [comment]
Pretty straight-forward usage I think...

```Python

         # create output factory and write out data stream
         urlTemplate = 'file://' + '{obs}{date:%Y%m%d}{t}' + mod_iaga + '{i}.{i}'
         out_factory = IAGA2002Factory(
            urlTemplate = urlTemplate
         )
         out_factory.put_timeseries(
               out_stream,
               starttime = out_start,
               endtime = out_end,
               channels = channels
         )

```

Of course adding `urlInterval=86400` fixed it. I don't have a problem with needing to explicitly pass this parameter, but as I noted originally, the docs (specifically, [docs/io.md](https://github.com/usgs/geomag-algorithms/blob/f398e16c6255dde5e6926b2dee63d18ae0538433/docs/io.md)) hinted strongly that 86400 was a default, so I thought maybe I was doing something wrong (e.g., something was incomplete or mis-configured in my output stream).

I'm just curious, what **is** the expected behavior with `urlInterval=-1` (assuming it is not an infinite loop)?

**Comment by jmfee-usgs** [comment]
For your example, I expect it would use "starttime" as the date to be formatted and include all data in the output file.
