### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ysshah** [usgs/geomag-algorithms#145]
I'm interested in adding Python 3 support to this library. Are there any incompatibilities with Python 3? Is anyone else already working on this?

**Comment by jmfee-usgs** [comment]
Python 3 is on our roadmap, but not at the top of the list.  We welcome contributions towards making this project compatible with python 3, but will need to maintain python 2.7 support for existing users.

The travis CI pipeline currently only runs tests against python 2.7, but 3 could be added here:
  https://github.com/usgs/geomag-algorithms/blob/master/.travis.yml
