### ISSUE TITLE
IAGA2002 factory and geomag web service produce different digital sampling values

### ISSUE THREAD

**Issue by hschovanec-usgs** [usgs/geomag-algorithms#173]
Entering the same parameters into the geomag web service and the IAGA2002 factory will produce different values for digital sampling.

Example:
- https://geomag.usgs.gov/ws/edge/?id=BOU&starttime=2017-08-01&endtime=2017-08-02&type=variation&sampling_period=60

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:
![screen shot 2017-08-24 at 1 21 41 pm](https://user-images.githubusercontent.com/26904055/29685087-985bce04-88d1-11e7-814f-03c9c7b87093.png)

- input_factory = geomagio.edge.EdgeFactory()
data = input_factory.get_timeseries(
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;observatory = 'BOU',
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;channels = ('X', 'Y', 'Z', 'F'),
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type = 'variation',
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;interval = 'minute',
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;starttime = UTCDateTime('2017-08-01'),
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;endtime = UTCDateTime('2017-08-02'))
output_factory = geomagio.iaga2002.IAGA2002Factory()
output_factory.write_file(
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;channels = ('X', 'Y', 'Z', 'F'),
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fh = sys.stdout,
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;timeseries = data)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:
![screen shot 2017-08-24 at 1 21 24 pm](https://user-images.githubusercontent.com/26904055/29685164-db68b0fe-88d1-11e7-9267-05eda8175fba.png)

**Comment by jmfee-usgs** [comment]
Fixed by #207
