### ISSUE TITLE
IAGA2002 Header element "Digital Sampling" not handled correctly

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#182]
https://github.com/usgs/geomag-algorithms/blob/aa6cdf686983ae0a6bbab38d008a4247988b6912/geomagio/iaga2002/IAGA2002Parser.py#L105

The IAGA2002 standard states that header element "Digital Sampling" is the rate (in seconds...yeah, I know that's not a rate) of sampling for the magnetic field sensor. However, is is apparently common for people (including the USGS, once upon a time) to put in things like "1 minute".

The IAGA2002 parser needs to be fixed to handle such values, or ignore them and not set the sensor_sampling_rate in the Trace's stats object.

**Comment by jmfee-usgs** [comment]
Fixed by #207
