### ISSUE TITLE
EdgeFactory _clean_timeseries sets the wrong trace starttime

### ISSUE THREAD

**Issue by arigdon-usgs** [usgs/geomag-algorithms#210]
When checking for gaps at the start of a trace, the _clean_timeseries method sets starttime to a potentially incorrect value.  Instead of setting to the requested starttime, it should calculate the time of the first valid sample time based on the number of samples prepended and the trace delta.  Same for endtime.

https://github.com/usgs/geomag-algorithms/blob/master/geomagio/edge/EdgeFactory.py#L229

**Comment by jmfee-usgs** [comment]
Fixed in #212
