### ISSUE TITLE
flake8 configuration doesn't ignore warnings

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#233]
It appears that the flake8 installed for our Py27 and Py36 Travis-CI setups is less permissive than that installed for Py34 and Py35. In particular, flake8 used in our Py27 and Py36 environments in Travis-CI fail with a flurry of pycodstyle 'warnings' (that is, 'W' codes).

I would like to go back to ignoring all 'W' codes, which I believe was the original intent for geomag-algorithms. Is this right? Or should we just add some specific 'W' codes to the ignore list in our .flake8 configuration file?

**Comment by erigler-usgs** [comment]
I understand that we have a geomag-algorithms coding standard.

The problem is that flake8 is behaving differently for different Travis-CI builds, presumably because something was never updated in the official Python 3.4.6 and 3.5.6 provided with Travis-CI. But frankly, this was a fortunate hiccup, because it helped uncover the bigger problem.

What I now believe happened (if I'm understanding even a little of the discussion here: https://gitlab.com/pycqa/flake8/issues/466), is that new warning's were added to pycodingstyle (W503 and it's counterpart, W504, which warn about line breaks before and after binary operators, respectively) relatively recently. By default, they should both be ignored by flake8, but because we use the `ignore` option in our .flake8 configuration file, any default ignores get wiped out, and both W503 and W504 get reported. That last is a real catch22, wouldn't you say?

So, we either need to add one or both of these to the ignore list in our own configuration file, or we can use the seemingly new flake8 option `extend-ignore`, so that we may benefit from the accumulated wisdom of flake8's savvy developers, and their own default ignore list.

**Comment by jmfee-usgs** [comment]
Closing now that we use `black` autoformatter instead of flake8
