### ISSUE TITLE
SqDistAlgorithm clarification requested

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#236]
https://github.com/usgs/geomag-algorithms/blob/7ea6bbeac7978377d8f365b36251a5de62ba2f42/geomagio/algorithm/SqDistAlgorithm.py#L222-L232

@jmfee-usgs, can you clarify what you meant by "state" and "process" in the line linked above? Or if this is a mistake (that is, the two should be swapped in the AlgorithmException string), let me know and I will submit a small fix.

FYI, I had assumed "state" meant the values stored in the state file or SqDistAlgorithm instance, and "process" meant whatever was contained in the trace that had been passed to SqDistAlgorithm's process_one() method. I ended up chasing a non-existent bug for almost an hour before figuring out the problem was in my statefile, not my inputs.

**Comment by jmfee-usgs** [comment]
@erigler-usgs yes, those words should be swapped.
