### ISSUE TITLE
FilterAlgorithm quietly fails if all specified input channels are not available

### ISSUE THREAD

**Issue by erigler-usgs** [usgs/geomag-algorithms#274]
If you specify (for example) `--inchannels H E Z F` for the Controller, and `F` is empty, the Filter algorithm will not return anything, even though H, E, and Z are perfectly good inputs.

The reason for this is that the default `can_produce_data` method for the parent Algorithm class that all specified `--inchannels` be available in order to return TRUE, otherwise it will not attempt to process any further

https://github.com/usgs/geomag-algorithms/blob/1c06af9d0a2e00b426da09c6b10417cc2ce9398c/geomagio/Controller.py#L268-L272

The fix should probably be for a `can_produce_data` method in FilterAlgorithm.py to return `True` if there are *any* traces in the passed stream. However, GitHub was kind enough to point out that this Issue is similar to #205, where I once proposed a similar "fix", but a slightly different approach was taken in the end. I would like to ping @jmfee-usgs to look at this briefly and weigh in with an opinion.

**Comment by jmfee-usgs** [comment]
The default behavior checks for gaps across all channels, which is valid for many algorithms.  In this case each channel is independently processed, so maybe something like "channel-foreach", similar to the observatory-foreach, where each channel is processed and gaps checked in serial?

**Comment by erigler-usgs** [comment]
That sounds interesting, but a little complicated. How do you handle situations where `--inchannels` and `--outchannels` differ? Or maybe worse, where there are a different number of `--outchannels` than `--inchannels`, like SqDistAlgorithm. I'm not sure I'm ready to dive into that just yet.

But after considering this in more detail, I can see why it may not be a good idea to just return `True` for `can_produce_data`, since each channel may very well have different gaps, and we wouldn't want to overwrite data in channel A when there was only a gap in channel B.

A short-term solution is to make separate calls in the scripts for each channel, which is something I feel confident in doing. If/when we get around to implementing some kind of "channels-foreach" option, it shouldn't break anything that is using only a single channel.

I'll leave this issue open for now, but probably won't work on myself it in the too near future.

**Comment by erigler-usgs** [comment]
Wow,  you are fast! I only submitted my comments 2 minutes before your pull request. ;-)

I'll look at the PR you submitted, but will you comment briefly on what I said above about possible complications?

**Comment by jmfee-usgs** [comment]
So I changed direction, instead of channel foreach which would make separate calls the FilterAlgorithm just returns true if any data exists for any channel (since this algorithm processes each channel seperately anyways.

The main risk is a gap in any output channel may result in reprocessing data for other input channels that already produced data.  Foreach would avoid this because it would check for gaps separately; however it would only work in situations where there is one input channel to be processed at a time.

Channel foreach may take more effort, but may also be a simpler solution in the long run
