### ISSUE TITLE
Double check filter algorithm output times to ensure they are centered

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#310]
Reported by @erigler-usgs : When the filter algorithm is called with the wrong data ( see #306 for an example where the times aren't correct ), it can shift the center of the filter window.  The data are correct, but the expected output data are shifted from the center of the second or minute.

The output start time is calculated after filtering the data:
https://github.com/usgs/geomag-algorithms/blob/master/geomagio/algorithm/FilterAlgorithm.py#L193

There are a couple options:
- detect the problem and raise ValueError if the resulting output time is not properly centered, something like this:

```
starttime % output_sample_period != 0
```

- fix the problem by detecting the problem, and filter only a subset of the data (by subsetting to the right) so any output values are at least properly centered

**Comment by pcain-usgs** [comment]
This issue was resolved in PR #311
