### ISSUE TITLE
improve install documentation

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#56]
"install" link on readme appears to be a header, figure out how to make it clearer.  review install documentation.

**Comment by jmfee-usgs** [comment]
touch on how to set up virtual environments

**Comment by emcwhirter-usgs** [comment]
This is how I got the project working on my Mac:
From this https://pip.readthedocs.org/en/stable/installing/#install-pip
 - Download `get-pip.py`
 - Run `python get-pip.py`

Then install obspy and other dependencies:
  `pip install numpy scipy obspy flake8`

After that I could run:
  `python geomagio/geomag.py -h`
