### ISSUE TITLE
determine edge channel names for sq/dist

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#63]

**Comment by emcwhirter-usgs** [comment]
This document contains all of Geomag's current SCNL's: 
  https://docs.google.com/spreadsheets/d/1Bxr_x0VyKI3BDeilB1dd8qkuK9wGQd97cKuxA5GkMn4/edit#gid=1790460847

The channel code is only allowed 3 characters. The network, location and observatory codes will match the input data. These might work as new channel codes:

 - ISQ (Index - Solar Quiet)
 - IDS (Index - Disturbance)
 - ITR (Index - Trend)

**Comment by jmfee-usgs** [comment]
I think we want the first character to still be the cadence, since we'll
likely offer seconds and minutes versions of these indices

**Comment by jmfee-usgs** [comment]
The document you shared shows MSQ for solar quiet and MDT for dist.

**Comment by emcwhirter-usgs** [comment]
True, but those were the previous iterations of those algorithms, so I wasn't sure if we wanted to re-use them on these. Also, if I understand correctly, we'll be running this algorithm on seconds data. Which would mean that we should use SSQ, SDT and maybe STR?

**Comment by jmfee-usgs** [comment]
- `MSQ` for minute solar quiet
- `MSV` for minute secular variation
- `MDT` for minute disturbance
