### ISSUE TITLE
prevent sqdist algorithm from running past end of input data.

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-algorithms#75]
The algorithm will currently try to process the entire requested range, leading to predicted SQ/SV and a potentially later filled Dist based on different info...

option:
- run in update mode which only tries to fill gaps in the output.
- add a --update-latest-only command line argument, and make run_as_update method filter the output_gaps list to the latest gap before continuing.
- I think we can still allow the update mode to recurse backwards, since it fills older gaps first which would allow the state to continue working; but it may also be worth having a way to prevent or limit this recursion.  It's possible you could override the can_produce_data method to prevent processing of any time spans before the next_starttime...

**Comment by emcwhirter-usgs** [comment]
Based on discussion, I think we only want to make sure we run in update mode for this ticket.  Instead of an update-latest-only option, we'll make the algorithm throw an exception if it processes data that would reset the state.
