### ISSUE TITLE
Make controller._get_output_timeseries handle renamed channels

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-algorithms#82]

**Comment by emcwhirter-usgs** [comment]
Controller in run_as_update mode requests output timeseries to check for gaps.  Output timeseries may be renamed before they are stored, and these renames need to be considered when looking for output gaps.

**Comment by jmfee-usgs** [comment]
this is not an issue right now, outchannels is requested which is the list that is actually stored after renaming.
